### ISSUE TITLE
Constants from lexical variables potentially modified elsewhere are deprecated

### ISSUE THREAD

**Issue by eserte** [Crowdtilt/Business-BalancedPayments#53]
Perl 5.21.7 has a new warning, which is causing the test suite to fail. See http://matrix.cpantesters.org/?dist=Business-BalancedPayments for a pass/fail test overview and http://www.cpantesters.org/cpan/report/df4303ae-8ad8-11e4-96b2-96d7e0bfc7aa for a sample fail report.

**Comment by garu** [comment]
Hi! Looks like this issue was already fixed upstream in Mouse. Is it safe to close this issue?

Cheers!

**Comment by eserte** [comment]
http://matrix.cpantesters.org/?dist=Business-BalancedPayments%201.0600 looks good for recent perls, so I'd say it's safe to close.
